### ISSUE TITLE
Write project overview for deliverable 1 due 3/16/21 Jacci

### ISSUE THREAD

**Issue by wpb911** [wpb911/omegaproject#6]
Complete project overview info and provide to Esteban

**Comment by jaccihorvath** [comment]
This application will take in the current date or allow users to search by month and/or specific produce item to determine which fruits and vegetables are in season. Users will be able to select an item to learn more about it, as well as see suggested recipes using the selected produce. Users can login to the app so to “favorite” fruits and save recipes. 

I believe this application is valuable because when I go to the grocery store without a specific produce item in mind, I would like to know which fruits and vegetables are in-season before making a purchase. There have been many times where I’ve purchased an item and ended up throwing it away because it was not ripe. 

Additionally, sometimes I buy produce items without having a plan for them and end up having to make an extra trip to the store to pick-up ingredients. This inconvenience could have been avoided had I done the appropriate planning, and this application takes everything I need to plan and puts it in one easily-accessible location.
